name: 'Action: 🦋 Changesets Release'
description: 'Release a new version of the package using changesets'

runs:
    using: "composite"

    steps:
        - name: Release
          id: changesets
          uses: changesets/action@v1
          with:
            version: yarn version
            publish: yarn release
            commit: "ci: release"
            title: "ci: release"
          env:
            # Disable husky
            HUSKY: 0
            GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ env.NPM_TOKEN }}
