name: Push to main

on:
    push:
        branches: [ main ]

permissions:
    actions: write
    checks: write
    contents: write
    deployments: write
    discussions: write
    issues: write
    packages: write
    id-token: write
    pull-requests: write
    repository-projects: write
    security-events: write
    statuses: write

jobs:
    build-test:
        strategy:
            matrix:
#                os: [ubuntu-latest, windows-latest]
                os: [ubuntu-latest]
        name: Build & Test  @ ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-node
            - uses: ./.github/actions/build
            - uses: ./.github/actions/test

    analyze:
        name: Analyze
        needs: build-test
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-node
            - uses: ./.github/actions/analyze

    build:
        needs: analyze
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-node
            - uses: ./.github/actions/build
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-node
            - uses: ./.github/actions/deploy
    release:
        name: Release
        needs: deploy
        # Sets permissions of the GITHUB_TOKEN to allow opening release PR
        permissions:
            id-token: write
            contents: write
            packages: write
            pull-requests: write
            issues: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-node
            - name: Release
              id: changesets
              uses: changesets/action@v1
              with:
                version: yarn version
                publish: yarn release
                commit: "ci: release"
                title: "ci: release"
              env:
                # Disable husky
                HUSKY: 0
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
